services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - app_data:/app/backend/data

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  app_data:
